apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "flask-postgres.fullname" . }}-flask

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ include "flask-postgres.fullname" . }}-flask

  template:
    metadata:
      labels:
        app: {{ include "flask-postgres.fullname" . }}-flask

    spec:
      containers:
        - name: flask

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: 5000
              protocol: TCP

          env:
            - name: DB_HOST
              value: {{ include "flask-postgres.fullname" . }}

            - name: DB_PORT
              value: "5432"

            - name: DB_NAME
              value: {{ .Values.postgres.database | quote }}

            - name: DB_USER
              value: {{ .Values.postgres.username | quote }}

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "flask-postgres.fullname" . }}-postgres
                  key: postgres-password

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
