apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "flask-postgres.fullname" . }}-postgres
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.postgres.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size }}
