replicaCount: 2

image:
  repository: shamsmo0h/flask-hello
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5000
  targetPort: 5000

postgres:
  image: postgres:17

  database: mydb
  username: postgres

  storage:
    size: 1Gi
    storageClass: longhorn

resources:
  requests:
    cpu: 100m
    memory: 128Mi

  limits:
    cpu: 500m
    memory: 512Mi
